name: Data Schema Code Convention Modified

on:
  push:
    branches:
      - main  

jobs:
  json_linter_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install JSON Linter
        run: npm install -g @prantlf/jsonlint

      - name: Run JSON Linter
        run: jsonlint $GITHUB_WORKSPACE/.github/workflows/DataSchemaModified.json
